// Generated by the Maven Archetype Plug-in
package it.xplants.VWDealersHub.app;

import org.apache.cayenne.ObjectContext;
import org.apache.cayenne.configuration.server.ServerRuntime;
import org.apache.cayenne.configuration.server.ServerRuntimeBuilder;
import org.apache.cayenne.log.JdbcEventLogger;
import org.apache.cayenne.log.NoopJdbcEventLogger;

import com.webobjects.appserver.WORequestHandler;
import com.webobjects.appserver.WOSession;
import com.webobjects.foundation.NSLog;
import er.extensions.appserver.ERXApplication;
import er.extensions.foundation.ERXPatcher;
import it.xplants.VWDealersHub.components.Main;

public class Application extends ERXApplication {
	public static void main(String[] argv) {
		ERXApplication.main(argv, Application.class);
	}

	private ServerRuntime cayenneRuntime;
	private ObjectContext objectContext;

	public Application() {
		super();
		
		String directActionRequestHandlerKey = this.directActionRequestHandlerKey();
		WORequestHandler directActionRequestHandler = this.requestHandlerForKey(directActionRequestHandlerKey);
		this.setDefaultRequestHandler(directActionRequestHandler);
		
		NSLog.out.appendln("Welcome to " + name() + " !");
		/* ** put your initialization code in here ** */

		ServerRuntimeBuilder config = ServerRuntime.builder();

		config = config.addConfig("cayenne-VWCMS.xml");
		if (!ERXApplication.erxApplication().isDevelopmentMode()) {
			config = config.addModule(binder -> binder.bind(JdbcEventLogger.class).to(NoopJdbcEventLogger.class));
		}
		this.cayenneRuntime = config.build();

		objectContext = cayenneRuntime.newContext();

	}

	public ObjectContext getObjectContext() {
		return objectContext;
	}

	/**
	 * Determines the WOSession class to instantiate.
	 * 
	 * @see com.webobjects.appserver.WOApplication#_sessionClass()
	 */
	@Override
	protected Class<? extends WOSession> _sessionClass() {
		return Session.class;
	}

	/**
	 * Install patches including ensuring that Main is correctly resolved at
	 * runtime.
	 * 
	 * @see er.extensions.appserver.ERXApplication#installPatches()
	 */
	@Override
	public void installPatches() {
		super.installPatches();
		ERXPatcher.setClassForName(Main.class, "Main");
	}
}
